development:
  adapter: postgresql
  encoding: unicode
  database: giant_robot_development
  pool: 5
  username: user
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: giant_robot_test
  pool: 5
  username: user
  password:
